### ISSUE TITLE
Not seeing much when running WhoopsExample

### ISSUE THREAD

**Issue by tipsy** [mschurr/spark-whoops#1]
I just cloned the repo and tried to run the example: 

![capture](https://cloud.githubusercontent.com/assets/1521451/13059951/2889a3de-d42e-11e5-9122-a4df81b714d3.PNG)

All the HTML/CSS/JS stuff seems to be missing.

**Comment by mschurr** [comment]
The top part shows the triggering exception, the bottom part shows that the exception that was thrown while trying to render the pretty error page.

I can't reproduce this on my machine. Can you take a look around and see if you can tell what is going wrong? Also, how are you running this and on what platform?

**Comment by tipsy** [comment]
I just cloned the repo and ran the WhoopsExample from IntelliJ. Tried it on both OSX El Capitan and Windows 10.

**Comment by tipsy** [comment]
Solved it by moving static resources to resource-folder and rewriting file-reading. I probably did something wrong, so I'll have a closer look tomorrow. This is really neat though :)

**Comment by mschurr** [comment]
Ah. I remember having this issue with some of my classmates. The Eclipse build process does copy static files outside of the resources folder into the build target folder, but IntelliJ does not.

If your changes fix this for IntelliJ users, feel free to submit a pull request. I'll make sure it still works with Eclipse.

**Comment by tipsy** [comment]
> If your changes fix this for IntelliJ users, feel free to submit a pull request. I'll make sure it still works with Eclipse.

I like this so much that I want to make it an official Spark Tool, which means we want to host the code ourselves and put it on Maven under Spark. Is that okay with you?

**Comment by mschurr** [comment]
That's fine with me.

**Comment by mschurr** [comment]
May want to do some code clean-up first and make it more extensible.

You'll also want to check with the guy who wrote https://github.com/filp/whoops, as this is heavily based off of his code (and is using some of it).

**Comment by mschurr** [comment]
Okay, I cleaned up the code a bit and applied a fix for the resource loading problem.

**Comment by tipsy** [comment]
> May want to do some code clean-up first and make it more extensible.

Yup, we need to make some HTML/CSS changes to make it fit better with Spark too. I will create some pull requests later when I have time :)

> You'll also want to check with the guy who wrote https://github.com/filp/whoops, as this is heavily based off of his code (and is using some of it).

Should be fine, it's MIT. Will credit the project though, he's done a great job.
